---
development:
  cloud_name: dowsq67bi
  api_key: '675834112123984'
  api_secret: sIIBKh1y8CTP4x6AYzGeot2xSB0
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dowsq67bi
  api_key: '675834112123984'
  api_secret: sIIBKh1y8CTP4x6AYzGeot2xSB0
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dowsq67bi
  api_key: '675834112123984'
  api_secret: sIIBKh1y8CTP4x6AYzGeot2xSB0
  enhance_image_tag: true
  static_image_support: false
